#!/usr/bin/env bash
# bash script to install and configure HAproxy on lb-01 server

#install HAproxy
echo -e "Updating and installing HAproxy...\n"
apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.8.\*

# create a backup of HAproxy configuration file
sudo cp /etc/haproxy/haproxy.cfg etc-haproxy-haproxy.cfg.backup

# configure HAproxy to send traffric to web-01 and web-02 servers
echo -e "Configuring HAproxy (Round Robin Algorithm) to send traffic to web-01 and web-02 servers...\n"
haproxy_confg=\
"
frontend Leumars_frontend
    bind *:80  # Listen on port 80 of all interfaces
    mode http
    default-backend Leumars_webservers  # Forward requests to webservers

  # Define backend servers
  backend Leumars_webservers
    balance roundrobin  # Use round-robin load balancing algorithm

    server web-01   54.157.155.48:80 check
    server web-02 	100.26.171.101:80 check
"

#shellcheck disable=SC2154
echo "$haproxy_confg" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable HAproxy to be started at boot time
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Test HAproxy configuration
echo -e "Testing HAproxy configuration...\n"
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# restart HAproxy
echo -e "Restarting HAproxy...\n"
sudo service haproxy restart

echo -e "\nCompleted.\n"
