#!/usr/bin/env bash
# A bash script that configures a server to listen on port 80 of all active IPv4 IPs

#create a symbolic link to the default nginx configuration file
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
#restart nginx
service nginx restart
#terminate the first nginx process
kill "$(pgrep 'nginx' | head -1)"
