#!/usr/bin/env bash
# A bash script that configures a server to listen on port 80 of all active IPv4 IPs
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
kill "$(pgrep 'nginx' | head -1)"
