#!/usr/bin/env bash
# a bash script that runs nginx as nginx user, and listens on port 8080

# check if nginx is installed
if ! [ -x "$(command -v nginx)" ]; then
  sudo apt-get update && sudo apt-get install nginx -y
fi
chmod 644 /etc/nginx/nginx.conf
sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
pkill apache2
# Change the port from 80 to 8080
#switch to the nginx user
su nginx -s /bin/bash -c 'service nginx restart'
